version: '3.7'
services:

  # RabbitMQ Instance
  rabbitmq:
    image: bitnami/rabbitmq:latest
    volumes:
    - /bitnami
    ports:
    - 5672:5672
    - 15672:15672

  postgres:
    image: bitnami/postgresql
    volumes:
    - /bitnami
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRESQL_DATABASE: media
    ports:
    - 5432:5432
  
  minio:
    image: minio/minio
    command:
    - server
    - /data
    volumes:
    - /data
    ports:
    - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "CHANGEME"
      MINIO_SECRET_KEY: "CHANGEME"

  ###########################################
  # Our Services
  converter:
    image: jaredallard/triton-converter:prod
    env_file:
    - .env
    volumes:
    - ./config:/mnt/config

  downloader:
    image: jaredallard/triton-downloader:prod
    env_file:
    - .env
    environment:
      ALLOW_FILE_URLS: 'true'
    volumes:
    - ./config:/mnt/config
    - /tmp/Bunny.mkv:/tmp/Bunny.mkv

  events:
    image: jaredallard/triton-events:prod
    env_file:
    - .env
    environment:
      NO_TRELLO: 'true' 
    command: events
    ports:
    - 3401:3401 # Webhook
    volumes:
    - ./config:/mnt/config

  beholder:
    image: jaredallard/triton-beholder:prod
    env_file:
    - .env
    environment:
      CONFIG_ENV: production
    command: beholder
    volumes:
    - ./config:/mnt/config

  twilight:
    image: jaredallard/triton-twilight-go
    env_file:
    - .env
    environment:
      TWILIGHT_STORAGE_PROVIDER: s3
      TWILIGHT_S3_BUCKET: 'triton-media'
      PORT: '8001'
    command: twilight
    ports:
    - 8001:8001
  
  identifier:
    image: jaredallard/triton-identifier
    restart: always
    env_file:
    - .env
    environment:
      IDENTIFIER_S3_BUCKET: 'triton-media'
    command: identifier
